NUM_DICE = 5
NUM_SIDES = 6
NUM_ROLLS = 3
NUM_TURNS = 13
UPPER_SECTION_BONUS_THRESHOLD = 63
UPPER_SECTION_BONUS_SCORE = 35
FULL_HOUSE_SCORE = 25
SMALL_STRAIGHT_SCORE = 30
LARGE_STRAIGHT_SCORE = 40
YAHTZEE_SCORE = 50
DEFAULT_NUM_SIMULATIONS = 10000
DEFAULT_VISUALIZATION_GAMES = 1000
DEFAULT_TOURNAMENT_GAMES = 500
DEFAULT_HEAD_TO_HEAD_GAMES = 1000
FIGURE_WIDTH = 12
FIGURE_HEIGHT = 8
LARGE_FIGURE_WIDTH = 14
LARGE_FIGURE_HEIGHT = 10
DETAILED_FIGURE_WIDTH = 15
DETAILED_FIGURE_HEIGHT = 10
HIST_BINS = 20
BAR_WIDTH = 0.2
RUNNING_AVG_WINDOW = 100
OUTPUT_DIR = "output"
COMPARISON_DIR = "output/comparison"
STRATEGIES_DIR = "output/strategies"
TOURNAMENT_DIR = "output/tournament"
SCORE_DIST_FILE = "score_distribution.png"
STRATEGY_COMP_FILE = "strategy_comparison.png"
TOURNAMENT_RESULTS_FILE = "tournament_results.png"

LOWER_QUARTILE = 25
UPPER_QUARTILE = 75
CATEGORY_ACES = "aces"
CATEGORY_TWOS = "twos"
CATEGORY_THREES = "threes"
CATEGORY_FOURS = "fours"
CATEGORY_FIVES = "fives"
CATEGORY_SIXES = "sixes"
CATEGORY_THREE_OF_A_KIND = "three of a kind"
CATEGORY_FOUR_OF_A_KIND = "four of a kind"
CATEGORY_FULL_HOUSE = "full house"
CATEGORY_SMALL_STRAIGHT = "small straight"
CATEGORY_LARGE_STRAIGHT = "large straight"
CATEGORY_YAHTZEE = "yahtzee"
CATEGORY_CHANCE = "chance"
SECTION_UPPER = "upper"
SECTION_LOWER = "lower"
CATEGORIES = {
    SECTION_UPPER: [CATEGORY_ACES, CATEGORY_TWOS, CATEGORY_THREES, CATEGORY_FOURS, CATEGORY_FIVES, CATEGORY_SIXES],
    SECTION_LOWER: [
        CATEGORY_THREE_OF_A_KIND,
        CATEGORY_FOUR_OF_A_KIND,
        CATEGORY_FULL_HOUSE,
        CATEGORY_SMALL_STRAIGHT,
        CATEGORY_LARGE_STRAIGHT,
        CATEGORY_YAHTZEE,
        CATEGORY_CHANCE
    ]
}

VALUES = {
    CATEGORY_ACES: 1, CATEGORY_TWOS: 2, CATEGORY_THREES: 3, 
    CATEGORY_FOURS: 4, CATEGORY_FIVES: 5, CATEGORY_SIXES: 6
}